# Generated by Django 3.0.9 on 2020-08-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(choices=[('SqFt', 'Sqft')], default='SqFt', max_length=32, verbose_name='AreaUnit')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Bathrooms')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Bedrooms')),
                ('home_size', models.PositiveIntegerField(null=True, verbose_name='Home Size')),
                ('home_type', models.CharField(choices=[('SingleFamily', 'Singlefamily'), ('Apartment', 'Apartment'), ('Condominium', 'Condominium'), ('Duplex', 'Duplex'), ('Miscellaneous', 'Miscellaneous'), ('MultiFamily2To4', 'Multifamily2To4'), ('VacantResidentialLand', 'Vacantresidentialland')], default='SingleFamily', max_length=32, verbose_name='HomeType')),
                ('last_sold_date', models.DateField(blank=True, null=True)),
                ('last_sold_price', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=16)),
                ('property_size', models.PositiveIntegerField(null=True, verbose_name='Property Size')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rent Price')),
                ('rentzestimate_amount', models.PositiveIntegerField()),
                ('rentzestimate_last_updated', models.DateField(blank=True, null=True)),
                ('tax_value', models.PositiveIntegerField()),
                ('tax_year', models.PositiveIntegerField(max_length=4)),
                ('year_built', models.PositiveIntegerField(max_length=4)),
                ('zestimate_amount', models.PositiveIntegerField()),
                ('zestimate_last_updated', models.DateField(blank=True, null=True)),
                ('zillow_id', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zipcode', models.CharField(max_length=16)),
            ],
        ),
    ]
